name: CI
on:
  push:
    branches:
      - yellowhank_develop
  pull_request:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
      - name: Build database
        run: docker-compose run mongodb
      - name: Build event bus
        run: docker-compose run n1.node
      - run: npm ci
      - run: npm test
  push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.CI_REGISTRY_USER }}/${{secrets.CI_REGISTRY}}:latest
